name: Check code when push

on:
  push:
    branches: Check
    - "main"

jobs:
  check-code:
    name: Check code
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - run: npm install
      - run: npm run ci